### ISSUE TITLE
解决移动1px --- less

### ISSUE THREAD

**Issue by signorhua** [signorhua/web-blog#46]
```javascript
.setTopLine(@c: #C7C7C7) {
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    right: 0;
    height: 1px;
    border-top: 1px solid @c;
    color: @c;
    transform-origin: 0 0;
    transform: scaleY(0.5);
}

.setBottomLine(@c: #C7C7C7) {
    content: " ";
    position: absolute;
    left: 0;
    bottom: 0;
    right: 0;
    height: 1px;
    border-bottom: 1px solid @c;
    color: @c;
    transform-origin: 0 100%;
    transform: scaleY(0.5);
}

.setLeftLine(@c: #C7C7C7) {
    content: " ";
    position: absolute;
    left: 0;
    top: 0;
    width: 1px;
    bottom: 0;
    border-left: 1px solid @c;
    color: @c;
    transform-origin: 0 0;
    transform: scaleX(0.5);
}

.setRightLine(@c: #C7C7C7) {
    content: " ";
    position: absolute;
    right: 0;
    top: 0;
    width: 1px;
    bottom: 0;
    border-right: 1px solid @c;
    color: @c;
    transform-origin: 100% 0;
    transform: scaleX(0.5);
}
```

https://github.com/Tencent/weui/blob/master/src/style/base/mixin/setOnepx.less

**Comment by signorhua** [comment]
配置 `postcss-write-svg` 实现 1px 任意边框，全边框

```css
@svg 1px-border {
  width: 4px;
  height: 4px;
  @rect {
    fill: transparent; 
    width: 100%;  
    height: 100%;  
    stroke-width: 25%;  
    stroke: var(--color, black);  
  }
  /*   
    border: 1px solid;
    border-image: svg(1px-border param(--color @color)) 1 stretch;  
  */
}
```

https://www.cnblogs.com/yikuu/p/9052148.html
